# Pacotes úteis

## Numpy

Principais utilidades: 
- Vetores (Arrays)
- Matrizes
- Números Aleatórios
- Operações com esses objetos
- Operações aritméticas

In [2]:
# importando
import numpy as np

Primeiro, vamos começar vendo como criar arrays e matrizes:

In [3]:
#criando um Array a partir de uma lista:
lista = [1,2,3,4,9]
meu_array = np.array(lista)
meu_array

array([1, 2, 3, 4, 9])

In [4]:
#criando matrizes: 
lista = [[1,2,3],[4,5,6],[6,7,8]] # observe que isso é uma lista que tem listas como argumentos

minha_matriz = np.array(lista)
minha_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

Porém, há diversas formas de gerar esses Arrays/matrizes:

#### numpy arange

In [5]:
#criando uma sequência de intervalos uniformes:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#criando uma sequência com saltos:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

#### numpy zeros e ones

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((7,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### numpy linspace
Cria, a partir de um intervalo, números igualmente espaçados

linspace(começo, fim, numero_de_numeros)

In [11]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### numpy eye
Cria a matriz identidade

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Números Aleatórios

#### numpy rand
Gera números aleatórios a partir de uma distribuição uniforme 0,1

In [13]:
np.random.rand(10)

array([0.54502557, 0.07456367, 0.59717117, 0.20924396, 0.98908408,
       0.65691273, 0.84380932, 0.66028681, 0.72713096, 0.98109192])

In [14]:
np.random.rand(4,4)

array([[0.52223008, 0.19724871, 0.47250401, 0.18742014],
       [0.07611779, 0.22049806, 0.55914984, 0.28024618],
       [0.74762845, 0.46808966, 0.44919298, 0.1532238 ],
       [0.21211208, 0.21231701, 0.44542982, 0.61107707]])

#### numpy randn
Gera números a partir de uma distribuição normal:

In [15]:
np.random.randn(10)

array([ 0.34351661,  0.28553292, -1.6208751 , -0.36663322,  0.43521977,
       -0.22796021,  2.17724791,  0.99212797,  2.35813963, -2.2116235 ])

#### numpy randint

Gera números inteiros aleatórios dentro do intervalo:

In [16]:
np.random.randint(10,100)

20

In [17]:
np.random.randint(10,100,10)

array([18, 14, 31, 48, 17, 26, 20, 89, 52, 85])

### Atributos e métodos úteis:

In [18]:
#Primeiro, vamos criar uma array para servir como base: 
meu_array = np.random.randint(0,100,25)
meu_array

array([27, 30, 75, 22, 70, 49, 93, 39,  3,  0,  8, 33, 40,  0, 65, 11, 54,
       53, 16, 69, 54, 37, 44, 68, 81])

#### reshape

In [19]:
#muda a dimensão:
meu_array.reshape(5,5)

array([[27, 30, 75, 22, 70],
       [49, 93, 39,  3,  0],
       [ 8, 33, 40,  0, 65],
       [11, 54, 53, 16, 69],
       [54, 37, 44, 68, 81]])

In [20]:
meu_array.reshape(25,1)

array([[27],
       [30],
       [75],
       [22],
       [70],
       [49],
       [93],
       [39],
       [ 3],
       [ 0],
       [ 8],
       [33],
       [40],
       [ 0],
       [65],
       [11],
       [54],
       [53],
       [16],
       [69],
       [54],
       [37],
       [44],
       [68],
       [81]])

#### max, min, argmax, argmin

In [21]:
np.max(meu_array)

93

In [22]:
np.argmax(meu_array)

6

### Operações com Arrays:

In [23]:
ar1 = np.arange(0,9)
ar2 = np.arange(5,14)
print(ar1)
print(ar2)

[0 1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10 11 12 13]


In [24]:
ar1 + ar2

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21])

In [25]:
ar1 * ar2 #multiplica individualmente cada elemento

array([  0,   6,  14,  24,  36,  50,  66,  84, 104])

In [26]:
ar1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [27]:
ar1 / ar2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444,
       0.5       , 0.54545455, 0.58333333, 0.61538462])

In [28]:
ar2 / ar1 #dividi por zero

C:\Users\Estudos\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 6.        , 3.5       , 2.66666667, 2.25      ,
       2.        , 1.83333333, 1.71428571, 1.625     ])

In [29]:
np.sqrt(ar1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [30]:
np.exp(ar1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [31]:
np.log(ar1)

C:\Users\Estudos\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [32]:
np.max(ar1) #mesma coisa do que o método .max()

8

In [33]:
np.sin(ar1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

### Pegando elementos de um array e uma matriz:


In [34]:
meu_array = np.arange(0,9)
minha_matriz = meu_array.reshape(3,3)

In [35]:
meu_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
meu_array[5]

5

In [37]:
meu_array[0:4]

array([0, 1, 2, 3])

In [38]:
minha_matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
minha_matriz[2] #retorna a terceira linha (python conta do zero, lembra?)

array([6, 7, 8])

In [40]:
minha_matriz[2][0]

6

In [41]:
#ou: 
minha_matriz[2,0]

6

In [42]:
#aqui, podemos mudar os elementos:
meu_array[0:4] = 100
meu_array

array([100, 100, 100, 100,   4,   5,   6,   7,   8])

In [43]:
#também podemos ter um problema: 
meu_array = np.arange(0,9)
meu_array2 = meu_array

In [44]:
meu_array2[0:3] = 100

In [45]:
meu_array

array([100, 100, 100,   3,   4,   5,   6,   7,   8])

In [46]:
#para resolver isso: 
meu_array = np.arange(0,9)
meu_array2 = meu_array.copy()  # aqui está o segredo
meu_array2[0:3] = 100
meu_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
# comparações:

In [48]:
meu_array > 4

array([False, False, False, False, False,  True,  True,  True,  True])

## Pandas

Serve para trabalharmos com Dataframes!

In [49]:
import pandas as pd

#### Importando um dataframe de um arquivo CSV:

In [50]:
df = pd.read_csv('example')
df

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

#### Exportando:

In [51]:
df.to_csv('example',index=False)

#### Excel? Mesma coisa!: 

In [52]:
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1') # importando

C:\Users\Estudos\Anaconda3\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)


0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [53]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1') #exportando

### Criando dataframes:

In [117]:
a = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
a

A   B key1
0  A0  B0   K0
1  A1  B1   K1
2  A2  B2   K2
3  A3  B3   K3

In [57]:
# a partir de uma matriz:
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A -1.585141 -0.172582  0.690523 -0.063948
B -1.276623 -0.682218 -0.614215  0.551012
C -0.024753 -1.685762  0.473714 -0.466793
D  0.647756  0.525254  1.450635 -0.047265
E -0.911567  0.658447  0.389953  0.286466

In [58]:
df

W         X         Y         Z
A -1.585141 -0.172582  0.690523 -0.063948
B -1.276623 -0.682218 -0.614215  0.551012
C -0.024753 -1.685762  0.473714 -0.466793
D  0.647756  0.525254  1.450635 -0.047265
E -0.911567  0.658447  0.389953  0.286466

#### Selecionando itens a partir de um dataframe:

In [59]:
df['W']

A   -1.585141
B   -1.276623
C   -0.024753
D    0.647756
E   -0.911567
Name: W, dtype: float64

In [60]:
df['W'][2]

-0.02475302722286369

In [79]:
df['W']['C']

-0.02475302722286369

In [81]:
df[['W', 'X']] #passando uma lista de argumentos, podemos mais de uma coluna:

W         X
A -1.585141 -0.172582
B -1.276623 -0.682218
C -0.024753 -1.685762
D  0.647756  0.525254
E -0.911567  0.658447

In [62]:
df.loc['A']

W   -1.585141
X   -0.172582
Y    0.690523
Z   -0.063948
Name: A, dtype: float64

In [63]:
df.iloc[0,:]

W   -1.585141
X   -0.172582
Y    0.690523
Z   -0.063948
Name: A, dtype: float64

In [64]:
df.iloc[1,3]

0.5510118906269087

#### Criando uma nova coluna:

In [65]:
df['nova'] = df['W'] + df['X']

In [66]:
df

W         X         Y         Z      nova
A -1.585141 -0.172582  0.690523 -0.063948 -1.757723
B -1.276623 -0.682218 -0.614215  0.551012 -1.958841
C -0.024753 -1.685762  0.473714 -0.466793 -1.710515
D  0.647756  0.525254  1.450635 -0.047265  1.173010
E -0.911567  0.658447  0.389953  0.286466 -0.253120

#### Removendo coluna:

In [69]:
df.drop('nova', axis = 1) #ou df.drop(columns = 'nova')

W         X         Y         Z
A -1.585141 -0.172582  0.690523 -0.063948
B -1.276623 -0.682218 -0.614215  0.551012
C -0.024753 -1.685762  0.473714 -0.466793
D  0.647756  0.525254  1.450635 -0.047265
E -0.911567  0.658447  0.389953  0.286466

In [70]:
df

W         X         Y         Z      nova
A -1.585141 -0.172582  0.690523 -0.063948 -1.757723
B -1.276623 -0.682218 -0.614215  0.551012 -1.958841
C -0.024753 -1.685762  0.473714 -0.466793 -1.710515
D  0.647756  0.525254  1.450635 -0.047265  1.173010
E -0.911567  0.658447  0.389953  0.286466 -0.253120

In [71]:
df = df.drop('nova', axis = 1)
df

W         X         Y         Z
A -1.585141 -0.172582  0.690523 -0.063948
B -1.276623 -0.682218 -0.614215  0.551012
C -0.024753 -1.685762  0.473714 -0.466793
D  0.647756  0.525254  1.450635 -0.047265
E -0.911567  0.658447  0.389953  0.286466

In [72]:
# ou: 
df['nova'] = df['W'] + df['X']
df.drop('nova', axis = 1, inplace = True)


### Selecionando com base em uma condição:

In [76]:
df > 0 

W      X      Y      Z
A  False  False   True  False
B  False  False  False   True
C  False  False   True  False
D   True   True   True  False
E  False   True   True   True

In [78]:
df[df>0] # isso faz com que só apareçam os valores que atendem a condição (x > 0) dentro do df

W         X         Y         Z
A       NaN       NaN  0.690523       NaN
B       NaN       NaN       NaN  0.551012
C       NaN       NaN  0.473714       NaN
D  0.647756  0.525254  1.450635       NaN
E       NaN  0.658447  0.389953  0.286466

In [86]:
#Podemos usar mais de uma condição também:
df[(df['W']>0) & (df['Y'] > 0)] #ele retorna só a linha em que W é positivo e Y também

W         X         Y         Z
D  0.647756  0.525254  1.450635 -0.047265

#### Índices

E se quisermos resetar os índices do DataFrame?

In [87]:
df.reset_index()

index         W         X         Y         Z
0     A -1.585141 -0.172582  0.690523 -0.063948
1     B -1.276623 -0.682218 -0.614215  0.551012
2     C -0.024753 -1.685762  0.473714 -0.466793
3     D  0.647756  0.525254  1.450635 -0.047265
4     E -0.911567  0.658447  0.389953  0.286466

E mudar?

In [91]:
df['empresas'] = 'VALE AMBEV PETROBRAS ITAU BRADESCO'.split() #isso cria uma coluna apenas
df

W         X         Y         Z   empresas
empresas                                                    
VALE      -1.585141 -0.172582  0.690523 -0.063948       VALE
AMBEV     -1.276623 -0.682218 -0.614215  0.551012      AMBEV
PETROBRAS -0.024753 -1.685762  0.473714 -0.466793  PETROBRAS
ITAU       0.647756  0.525254  1.450635 -0.047265       ITAU
BRADESCO  -0.911567  0.658447  0.389953  0.286466   BRADESCO

In [92]:
df.set_index('empresas',inplace=True) # isso aqui muda
df

W         X         Y         Z
empresas                                         
VALE      -1.585141 -0.172582  0.690523 -0.063948
AMBEV     -1.276623 -0.682218 -0.614215  0.551012
PETROBRAS -0.024753 -1.685762  0.473714 -0.466793
ITAU       0.647756  0.525254  1.450635 -0.047265
BRADESCO  -0.911567  0.658447  0.389953  0.286466

### Lidando com dados faltantes: 

In [95]:
#criando os dados:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [97]:
df.dropna() #simplesmente tira todas as linhas que tem NA

A    B  C
0  1.0  5.0  1

In [100]:
df.dropna(axis=1) #ou as colunas se especificarmos

C
0  1
1  2
2  3

E se quisermos __preencher__ os dados NA?

In [101]:
df.fillna(value='PREENCHA COM ISSO')

A                  B  C
0                  1                  5  1
1                  2  PREENCHA COM ISSO  2
2  PREENCHA COM ISSO  PREENCHA COM ISSO  3

In [103]:
df['A'].fillna(value=df['A'].mean()) # substitui em A

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [104]:
df['A'].fillna(value=df['A'].median())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [105]:
#observe que não muda o data frame... precisaríamos setar o dataframe novo: 

In [106]:
df['A'] = df['A'].fillna(value=df['A'].median())

In [107]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

### Lidando com DataFrames - Merging, joining e concatenating:

In [109]:
#criando os dados:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [110]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [111]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [112]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#### Concatenating: 
 Simplesmente junta os dataframes por linha (axis = 0 padrão) ou coluna (axis = 1)

In [115]:
pd.concat([df1,df2,df3]) #axis = 0

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [116]:
pd.concat([df1,df2,df3], axis = 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#### Merging Dataframes:

In [122]:
#Criando os dados
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})   
print(left)
print( )
print(right)

    A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

    C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3


In [124]:
pd.merge(left,right,how='inner',on='key') #esse combina pela chave, que é a mesma nos dois!

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

#### Joining

In [126]:
#criando os dados:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [128]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [129]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [130]:
left.join(right) #Observe que a coluna k3 do right some

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [132]:
left.join(right, how='outer') #nesse aqui, nada some, só aparecem uns NAs

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

### Operações:

In [133]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [134]:
df['col2'].unique() #retorna os valores únicos

array([444, 555, 666], dtype=int64)

In [136]:
df['col2'].nunique() #retorna os número de valores únicos

3

In [137]:
df['col2'].value_counts() #retorna a contagem dos valores 

444    2
555    1
666    1
Name: col2, dtype: int64

In [139]:
#aplicando funções:

df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [141]:
df.iloc[:,1].mean()

527.25

In [143]:
def vezesdois(x):
    return 2 * x

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [148]:
df.apply(vezesdois)

col1  col2    col3
0     2   888  abcabc
1     4  1110  defdef
2     6  1332  ghighi
3     8   888  xyzxyz

Lembra que deletamos uma coluna com o .drop? Tem outro jeito:

In [149]:
del df['col1']

In [150]:
df.columns #retorna os nomes das colunas 

Index(['col2', 'col3'], dtype='object')

In [151]:
df.index #retorna os índices

RangeIndex(start=0, stop=4, step=1)

Podemos alterar a ordem do dataframe com base nos dados de uma coluna também:

In [152]:
df.sort_values(by='col2') #inplace=False por default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

# Para casa

#### Visualização: 

Aprenda o básico de visualização com python (matplotlib) com base nos seguintes materiais: 
- https://www.youtube.com/watch?v=q7Bo_J8x_dw&list=PLQVvvaa0QuDfefDfXb9Yf0la1fPDKluPF
- https://www.youtube.com/watch?v=aCULcv_IQYw&list=PLQVvvaa0QuDfefDfXb9Yf0la1fPDKluPF&index=2
- https://www.youtube.com/watch?v=ZyTO4SwhSeE&index=3&list=PLQVvvaa0QuDfefDfXb9Yf0la1fPDKluPF
- https://www.youtube.com/watch?v=WbTOutpwPHs&index=4&list=PLQVvvaa0QuDfefDfXb9Yf0la1fPDKluPF 

Se quiser se aprender mais fundo, procure também materiais sobre Seaborn. Eles serão usados nas próximas aulas.

#### Prática:

Pratique o que vimos hoje tentando importar dados de CSV ou do excel.
Se possível entre no desafio: https://www.kaggle.com/c/titanic
baixe os dados (CSV: train.csv, test.csv), importe-os para o python como DataFrame e comece a visualizar os dados, usando o que você aprendeu com o matplotlib/seaborn. Tente ver quais as colunas tem mais NAs (Desafio), remova as que tem muitos do Dataframe e substitua os NAs das que tem pouco pelo que você achar melhor! Ex: preencha com a média